### ISSUE TITLE
All of our tweets should be in code

### ISSUE THREAD

**Issue by danigrant** [TechAtNYU/techatnyu#1]
Example:

HackDay.create(:time => 300, :room => "uc-24")

**Comment by ethanresnick** [comment]
I'm totally on board with this for Hack Days. But for the other initiatives I worry that this might scare designers away. (Some designers have already told me they felt like Hack Nights wasn't for them.) Maybe we could use this for Hack Days and come up with a different style for our other initiatives—but one that's still more interesting than normal text?

//cc @abhinayashutosh

**Comment by danigrant** [comment]
Agreed!

**Comment by ethanresnick** [comment]
Ok, awesome. So, unless @AbhiAgarwal has any objections, we're doing this next semester!

We could even do it in whatever language Hack Days is teaching/using that week. So a Ruby workshop would look like the example you posted. Js could be:

```
new HackDays({title:'Intro to Angular', room: 'Courant 201', dateTime: new Date('tomorrow at 3pm'), details: http://www.techatnyu.org/whatever})
```

And SQL:

```
INSERT INTO HackDays (title, room, date, details) VALUES ('Intro to SQL', 'Courant 201', '2014-04-05 03:00:00', 'http://www.techatnyu.org/whatever')
```

**Comment by BenPaster** [comment]
Although, we run the risk of everyone criticizing our code!

```
INSERT INTO HackDays (`title`, `room`, `date`, `details`) VALUES ('Intro to SQL', 'Courant 201', '2014-04-05 03:00:00', 'http://www.techatnyu.org/whatever')
```

#iwentthere

**Comment by ethanresnick** [comment]
Haha, yep. Been a while since I wrote any raw sql :)

Edit: although, actually, no backquotes would've been ok if I hadn't I named a field date.

**Comment by AbhiAgarwal** [comment]
Cool use cases:

```
if @hacker.is_awesome? && @hacker.internship.blank?
Mail.deliver do
from @hacker.email
to 'hi@mlh.io'
subject 'hackers gonna hack'
body 'Yo dawg, I herd u liek hacking so I put some hack on your hack so you can hack while you hack'
add_file @hacker.resume
end
```

(https://www.facebook.com/photo.php?fbid=10151989540556612&set=gm.697913000246760&type=1&theater)

This is actually pretty cool

**Comment by ethanresnick** [comment]
+1
