### ISSUE TITLE
tech@nyu paypal account

### ISSUE THREAD

**Issue by terriburns** [TechAtNYU/techatnyu#10]
Is there any way we can create a tech@nyu paypal account? I know that in the past we have used Emanuel's, but I feel like for the sake of professionalism (when trying to get companies + administration + alum + etc to give us money)  we should try to get one specifically addressed to tech@nyu.

**Comment by hahnbo** [comment]
Haha so actually my account is a business account set as 'tech@nyu'

It would be a good idea to link a new payal account with an official
tech@nyu email tho. Something like payments@techatnyu.org

**Comment by revivek** [comment]
Don't paypal accounts need to be hooked up to a bank account?—

**Comment by grungerabbit** [comment]
This article might be useful, if we do get a full financial setup with bank account and paypal https://students.ucsd.edu/student-life/involvement/organizations/financial-processes/bank-accounts.html

**Comment by ethanresnick** [comment]
I absolutely think we should make a tech@nyu bank account, so we always know how much money's on hand, where it came from, etc. We can give the whole board the password to a Mint account that's connected to it (essentially giving them read-only access), so everyone can see where the money's going. Then we can link it to a tech@nyu paypal, or eve have companies send us checks directly.

**Comment by ethanresnick** [comment]
If people agree with this, I'll take care of it tomorrow.

**Comment by grungerabbit** [comment]
Using Mint for read-only is an excellent idea. 

@ethanresnick we should take our time to research and negotiate with the financial institution that will give us the best terms (possibility: [NYUFCU](http://www.nyufcu.com/ASP/home.asp), though I know little about them besides the NYU affiliation).

**Comment by ethanresnick** [comment]
There's also [this](http://www.nyu.edu/content/dam/nyu/studentActivities/documents/clubs/club-guide-oct-2012.pdf):

> 154: Unauthorized Bank Accounts - All-Square clubs are not authorized to set up accounts with banks or other like institutions or use personal checking or savings accounts to hold club income.

It might be outdated, we should probably ask first.

**Comment by revivek** [comment]
@ethanresnick yeah, that rule was why we didn't before. Worth checking on but don't spend too much time on it. We've made that mistake before.

It'd have to be under a personal account, since we aren't legally a business or non profit.

—
