### ISSUE TITLE
techatnyu.org email addresses for initiatives

### ISSUE THREAD

**Issue by grungerabbit** [TechAtNYU/techatnyu#11]
e.g, demodays@techatnyu.org or operations@techatnyu.org

Along the lines of @terriburns's excellent suggestion #10, we should have emails per initiative for transparency and archival reasons:
- Another digital backup of institutional memory
- Let future members learn logistics (like how to cold email or arrange catering)
- Abstract tech@nyu correspondence from personal accounts
- Outsiders know more precisely how to contact us, instead of the current catch-all email
- Account can be maintained by whoever is current head of initiative
- The president (or the platform) can keep a store of all passwords in case of emergency
- Public facing website format includes current eboard to retain accountability: e.g., "please email Cheryl at jobs@techatnyu.org"

**Comment by ethanresnick** [comment]
Ooh, I like this. I was going to start an issue asking about us all getting ourname@techatnyu.org emails, which still might be a nice perk to offer eboard members. But for mailing people and receiving mail about our initiatives, your idea makes more sense.

@AbhiAgarwal Can you set it up?

**Comment by abhiagar** [comment]
I'm on it! sorry about the different username.. Mine was locked out of 2-factor auth (not in the U.S.)

Edit: This is a pain actually. I'm not sure who owns the admin@techatnyu.org. It's hosted ontop of Google Mail for organizations, etc. So We've to login to admin@techatnyu.org through Gmail and then we can use the administration section to create more emails.

**Comment by rgardner** [comment]
@abhiagar Are you able to sign in?

**Comment by revivek** [comment]
Jared set Gmail up a while ago. Let me know if we should loop him in.—

**Comment by abhiagar** [comment]
Someone has verification enabled on it I believe. So I kind of need to know who's device before setting up these emails!

**Comment by revivek** [comment]
Maybe just send the verification and we can see who has it hooked up to their device.—

**Comment by wyattisimo** [comment]
I put the credentials in Passpack when I set up the Google apps account.
Are you guys still using Passpack?

Jared

**Comment by ethanresnick** [comment]
Yeah, we have the passpack and it has the code, but Google's asking for verification when I sign in. (Not standard two-factor auth, though; instead, it seems I tripped some anomaly detection algorithm, as it's just asking me to verify the phone number on the account.) @wyattisimo I'll send you an email with the details. Can I send it to proxy@wyatt.co?

**Comment by wyattisimo** [comment]
Maybe Google doesn't like your IP address.
http://media.giphy.com/media/9jAFNVAhmjG92/giphy.gif

I just logged in with no problems.
http://media.giphy.com/media/pq9EZOZCsFV8Q/giphy.gif

I looked at the account info and it shows the phone number is (347)
606-8244.
http://media.giphy.com/media/XuKEscwZW4c80/giphy.gif

You can reach me at j@wyatt.co.

**Comment by ethanresnick** [comment]
Yep, was probably IP or similar. Either way, no that I gave them the phone number, it worked. I'll set up the emails.

**Comment by wyattisimo** [comment]
bee tee dubs, when I logged in, I noticed several groups that were set up
many moons ago to forward email to various officers in charge of specific
initiatives. Might want to clean those up.

**Comment by ethanresnick** [comment]
Thanks! I'll take a look.
