### ISSUE TITLE
Recruiting agencies/recruiters for event sponsors?

### ISSUE THREAD

**Issue by grungerabbit** [TechAtNYU/techatnyu#12]
Any strong feelings about that? I'm at a Javascript conference in Philly right now and their sponsors are all local staffing agencies. (To supplant, not replace companies for sponsors)

**Comment by ethanresnick** [comment]
What seems to be the deal? Just displaying the agency's name in exchange for cash? Or somehow giving the agency (hopefully opt-in, or at least very clearly opt-out) info about the attendees?

**Comment by grungerabbit** [comment]
Display agency name on marketing material (site/shirt/deck) + short pitch at event + informal hangout at event. No data provided about attendees in aggregate. We could change this format, though, that's just what I observed.

I know we discourage recruiters at events, but not sure if we've used (or want to use) them as a sponsor source?
