### ISSUE TITLE
Host small, informal and mostly-non-technical discussions a la Stanford Salon Series

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/techatnyu#3]
An interesting idea, esp. if someone outside our club is willing to help with organizing. Stacey Ferreira brought it up and wants to be involved. For now, I'm just documenting it here.

**Comment by revivek** [comment]
Agreed! We had these for a whole, called Tech@NYU Roundtables. They were quite stimulating. Happy to loop in Ali Shah who ran them for a few months. Let me know.

**Comment by ethanresnick** [comment]
Closing this as an interesting idea to revisit later. For now we need to focus on doing well the initiatives we're already doing.

**Comment by rgardner** [comment]
One alternative to a new initiative could be partnering with existing clubs/organizations/people that do this. Something like [Stanford Salon Meets NYC](https://www.facebook.com/events/246305468903560/).
The description from the FB event:

> Every Monday, come out for a night of meeting awesome new people and sharing ideas you're passionate about! 
> The format is as follows: 
> - Everyone introduces themselves briefly. 
> - 3 people every monday have 15 minutes to share a concept, idea or thought they've been interested in that week or in general (note: not company pitches). 
> - After each talk, we'll have time to start a discussion about the topic with others.
