### ISSUE TITLE
Blog Description

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/techatnyu#4]
Right now, the tagline on the blog is:

> Design. Build. Code. Launch. 
> Reach us at hello@techatnyu.org

I like that we have the contact info (we should definitely keep that), but I think it might be good to have a slightly longer description of what we do, for people who just land on the page. (Maybe this description would go at the top of a left hand sidebar or something, when we get around to redesigning the blog.)

If you guys agree, can one of you (@BrittanyV, @tommycollison, @abhinayashutosh) update the description as you see fit. If not, let's discuss.

(An obvious description to grab would be the one we're using on the main site's homepage, but it doesn't have to be that word-for-word.)

**Comment by tommycollison** [comment]
Yep I'm down with changing the blog description to what's on the site. If nobody has any issues, I'll update it tonight. On a purely semantic level, we could shorten it a bit by putting the note about experience levels in the first sentence: "We host tech, design, and entrepreneurship events for students of all experience levels at NYU and surrounding schools."

Apologies for not getting to blog stuff before now -- settled in SF and can devote full attention to it.

-- TC

**Comment by ethanresnick** [comment]
Saw that you updated it. Looks perfect. Thanks man.
