### ISSUE TITLE
HackDays

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/techatnyu#6]
This was here: https://gist.github.com/AbhiAgarwal/89c69763ee0e8c5119ea

I'm moving it for other people to comment.
- I want to rebrand HackDays this semester. I'm going to move away from teaching super beginner things and actually bring out the real stuff. I want to bring people in to teach things like Machine Learning, Facial Recognition and/or Detection, Image Analysis, and so much more. Teach people how to build web frameworks rather than teaching people how to use them, and help them understand what goes on in the real world rather than helping them understand for loops.
- I want to understand how people want me to proceed. I don't quite know what to do at this stage. I feel like I have a lot to teach or a lot to help people with. I'm dedicated to learning new things and helping people learn them in the process, but I don't know what people want to learn. I don't really want to teach people Python or Javascript.
- I can bring in students who know Machine Learning, or OpenCV, or OpenGL and let them help students learn those things. Do you think that's the right way we should do it? I don't really want to target people who are beginning to program anymore, but to target people who are passionate about it.
- What are you opinions?

@rgardner Response:

"I like it! One option for finding out what people want is polling them. Reaching out to existing members, ACM, friends, previous students from past classes, etc with either a personal message and/or a google form.

I'm so pumped, beginner workshops get so boring, especially if that's all we do. I am worried that we'll alienate beginners - we should work on getting that resource repo production ready by the time school starts. Offer support in either a monthly event or provide some hands on time in a HackNights setting - I don't know).

For getting those speakers, reaching out to professors for specific fields as well as companies (I think big ones would be better than start ups, but maybe that's my own bias)."

@abhiagarwal Response:

"Good to know! I enjoy startups a little more because their implementations are usually manageable and able to be shown to the public. For example, a startup would be able to explain their Machine Learning implementation more than someone at Microsoft could because of the complexity behind them, and layers of abstraction. I agree with you in both regards - I would love to see people from both large companies and small companies.

I think I will give the teaching beginner workshops to someone else or create it as a separate event. I had a lot of problems last year regarding it, and I don't think it's something that's for most people. I would be more comfortable sitting with someone and teaching them Python rather than presenting it as it benefits people more. I would be happy to do things like sitdown learning of languages 1v1 rather than the an event out of it.

I will probably reach out to most my classmates, which I have experiences with. I think that's a good case for me because I know how they teach or know how they learn so it becomes a little easier to manage. I would be down to have people come present things like Competitive Programming or ACM so people can exposure to what those things are."

@ethanresnick Response:

"Hey Abhi,

I hear you about your not wanting to teach more beginner workshops and I think that's fine, as long as tech@nyu offers something for beginners elsewhere. How do you feel about this:

We change HackDays talks to be more technical, as you're describing. To figure out the exact topics, maybe we poll students, as Bob suggested. Reaching out to your classmates sounds like a good idea. (Also, if you think any of them would be good for our board or the Hack Days team, maybe to help you organize these events, try to recruit them. If they seem interested, please put me in touch with them too.)

We help out beginners one-on-one at HackNights, as you guys mentioned. You could formally join the Hack Nights team, which would basically mean doing what you were already doing last year: coming out to hack nights each week (or most weeks) and helping people out one-on-one.

We actually launch our resources project before the start of next semester. Or, maybe we just work with Columbia to make their list of beginner resources better/more detailed, rather than building our own from scratch."

Any other opinions?

**Comment by ethanresnick** [comment]
Awesome. Thanks for moving!

**Comment by ethanresnick** [comment]
Following up on this.... @AbhiAgarwal, how do you feel about the option I suggested in my last comment on the thread (from the gist)? 

That is:
1. We make Hack Days more technical, with no more beginner talks
2. We get the resources launched (with Columbia or otherwise) for the start of school
3. You continue to come to HackNights regularly to help people out

I think the above would leave us in a very good position to cater to the the more advanced people and do talks that are more interesting, while also leaving some supporting structures for beginners.

**Comment by abhiagar** [comment]
Sure. I completely agree. Lets point the new people to HackNights, and I'll try my hardest to be at every event. 

I'm going to be releasing a lot of resources before the university starts for Freshman Circuit (@freialobo). So they can start learning about our industry asap. I have a lot of leads on talks, and I have contacted a few people so we're ready to go on that front.

**Comment by ethanresnick** [comment]
Perfect! I'm going to close this issue then as resolved!
