### ISSUE TITLE
Renaming Hack Days?

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/techatnyu#7]
Hack Days's name doesn't really communicate what it's about imo (technical talks or live coding). Meanwhile, it gets confused with HackNights, which I think is actually aptly named.

If you guys agree, let's rename it. Any naming ideas? @AbhiAgarwal @rgardner @danigrant @BenPaster @abhinayashutosh @revivek @grungerabbit

**Comment by grungerabbit** [comment]
notes from retreat 7/12/2014

# Problems
- Too close to each other to be distinctive, meaningful
- Designers don't think they are included in "Hack[X]"
- No real reason for symmetry (see caveat)

**What are we trying to get out of this name?**
- Distinguishes between Days are talks and Nights are social
- Accessible to programmers, designers, gamers, businesspeople
- Unified scheme for initiatives that are tech@NYU

"Hacking is about building something that's cool and it's like... a widget, not something that is a product... building for the purposes of learning or exploring a problem space, but not something someone would use necessarily" @revivek 

"It could be a product, it could be doing your CS homework with friends... or coming and playing around with Angular" @ethanresnick 

**Legacy (Hursh-era) HackDays has migrated to HackNights, HackDays is a lecture with code-along** (Not that much code-along in practice @hahnbo ... become more advanced @AbhiAgarwal)

# Definitions

**HackDays**
Hardcore tech workshops

**HackNights**
More robust hangout + show and tell + help/office hours
- Programmers - design for machines and other programmers
- Designers - design for humans, may not know how to code

# Ideas
- Make
  - A little hardware-ish?
- Build
- Hack and Design? (Too close to Design and Code)
- Random name not associated with those words
- "Workshop" for HD
- Collective
- Craft
- Create
- Labs, experiment
- Makerdays
- Hackerlab

**Comment by jjmalina** [comment]
HackShops?

**Comment by AbhiAgarwal** [comment]
LearnDays? It's a little weird though, but I think it sort of meets your requirement? It kind of goes off the whole hacking/cs thing though..

**Comment by ethanresnick** [comment]
Rough ideas...

_For HackDays:_
- `CS++` 
- `CS.pop()` (When marketing a specific talk, we'd put its name as the argument.)

_For HackNights:_
- `crit && code`
- design, tech, and a `break;`
- form and `function`

## 

The above are probably my favorites of the ones I came up with, though I don't think any of them are very good yet. In case it inspires anyone, here are some of the other ones I came up with:
- Creation Collective
- Collective Creation
- HackCollective
- `build build && learn` 
- `make ___` (where underscores would be replaced by the name of each talk)
- `make cs-talk` or `make code-talks`
- TechBits <-- Look out Dani
- TechLab
- Hackers' Workshop
- `techSkills++`
- `csWorkshops++`
- `create++`
- code + craft
- Humans of CS
- `code && design`
- design + build
- code and humans
- learn, craft + hack
- CodeShop
- Hack, Talk, Build
- CSTalks
- Talking Code
- `make cs`
- `union(design, code, humans)`
- design ∪ code ∪ food
- craft ux and `make code`
- `code break;`

Also, I wrote a function that combines these words quasi-randomly. Could lead to some interesting ideas...

```
function name() {
  var words = ['make', 'hack', 'build', 'design', 'ux', 'create', 'function', 'switch', 'craft', 'tech', 'code', 'cs', 'learn', 'humans', 'teach', 'flow', 'crit'];
  var joiners = ['and', 'workshop', 'collective', 'lab', 'class', 'break;', 'push()', 'pop()', 'talks', 'nights'];
  var operators = ['+', '++', '&&'];
  var wordCount = (Math.floor(Math.random()*3) + 1);
  var joinerCount = Math.round(Math.random()*2);
  var operatorCount = Math.round(Math.random());
  var name = [];

  for(var i=0; i<wordCount; i++) {
     name.push(words[Math.floor(Math.random()*words.length)]);
  }

  for(var j=0; j<joinerCount; j++) {
    name.splice(-1*j, 0, joiners[Math.floor(Math.random()*joiners.length)]);
  }

  if(operatorCount) {
    name.splice((1+Math.round(Math.random())), 0, operators[Math.floor(Math.random()*operators.length)]);
  }

  return name.join(' ');
}
```

**Comment by rgardner** [comment]
For HackDays, how about "After Hours"? Something that invokes an after school program. This captures the learning aspect of it, but doesn't necessarily imply design, programming, or hardware. This allows HackDays to cover a wide range of topics; though maybe it should be more focused, considering we have a DesignDays initiative.

**Comment by ethanresnick** [comment]
Hmmm...to me, After Hours sounds like a name for HackNights (people hanging out after school) rather than for HackDays. And as a HackNights name, I like it.

**Comment by grungerabbit** [comment]
@ethanresnick form and function() is adorable

I think After Hours is a good way to go for HackNights.

**Comment by grungerabbit** [comment]
Hack@UChicago's Hack Nights: https://hack.uchicago.edu/hack-nights/new-to-hack-night/

I think their "introductions" are similar to what I wanted with the "show and tell/office hours" part of HN (also, see HackNights currency as a term established independently of t@NYU. Not sure if this is a compelling reason to keep or rebrand...)

**Comment by ethanresnick** [comment]
My current thought: let's keep Hack Days named as it is and rename Hack Nights to After Hours. That solves the problem of communicating that Hack Nights is for more than just programmers, and it makes it more distinct from Hack Days. It also implies that the event is a little more social.

**Comment by abhiagar** [comment]
I agree with @ethanresnick. I think HackDays name should stay. I think many people identify this even with the name HackDays, and I think it's appropriate in my opinion. 'Hack' has a lot of meanings I think it could be identified as the one above.

**Comment by rgardner** [comment]
:+1:

To help with HackDays definition, I think one of our first digests should be all about the words 'Hack' and 'Hacker'. We'd link to League of Hackers, other schools (like [UChicago](https://hack.uchicago.edu/hack-nights/new-to-hack-night/)), [Eric Raymond (pioneer of open source)](http://www.catb.org/esr/faqs/hacker-howto.html), [Paul Graham](http://www.paulgraham.com/gba.html), and more.

**Comment by ethanresnick** [comment]
@rgardner Totally agree about the digest; that's a good place to have the 'meaning of hacking' conversation. Re your thumbs up: does it refer only to keeping the Hack Days name, or also to using After Hours as the name for Hack Nights?

**Comment by rgardner** [comment]
Both, I like the HackNights change to After Hours and that HackDays will keep its original name.

**Comment by ethanresnick** [comment]
Sounds good. I'm gonna close this then and we'll After Hours as the name going forward.
