### ISSUE TITLE
New Initiative ("Good Days"-esque)

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/techatnyu#8]
Dario, a HackNights regular who's talked to me about getting more involved, proposed this initiative (copied from his email).

---

Hey! 
So I have an idea for an initiative that could kinda combine other initiatives. For some reason I really enjoy volunteering and giving back to the community, soup kitchens, beach cleanup, etc. During my senior year of high school I wanted to combine my obsession with technology and my weird love for volunteering, originally the plan was to recruit different coders from my school and build some awesome stuff for non-profit open source organizations, but my school didn't really have that many coders so instead I decided to organize a huge fundraiser to purchase laptops from OLPC and send them to a small village in Colombia. The project was awesome but I still wanna experiment with my first idea, so (getting back to the topic haha) my suggestion is to create service initiative that could organize different kind of events, from having days(or weeks or months) where a group of people can make awesome open source projects (design and hackday!)  to having a team bonding day helping with the sandy relief efforts or cleaning the beach and then just have a beach day! I know it would take a lot but I really think it would be really awesome and fun. Also I really like Design days and would like to help there too if its ok, I believe that this part of the club could really offer something amazing and be the design major NYU never had. I'm majoring in CS and minoring in Studio Art, so I could help the club better combine code and design! Haha so many ideas that if wrote them all it would take a while! 

Let me know what you think, and see if I can help out in anyway!
Dario

**Comment by ethanresnick** [comment]
Hey Dario,

I like your ideas and I think there are definitely ways you can help out!

I think we should try these ideas out first as parts of other initiatives; then, if they really take off and are running smoothly, we can make an initiative dedicated only to service. Here's what I'd suggest right now: 

— If @rgardner's ok with it, you can join the HackNights team and organize a HackNights next semester that's themed around making open-source contributions (particularly to philanthropic organizations/goals).

— You can join our new community team, which is focused on planning events for our community and board, and plan a beach outing like the one you described (or other service–fun hybrid events).

— You can join the design days team and help out there as needed.

Does that sound good? Am I missing anything?

**Comment by rgardner** [comment]
That sounds great to me. I like the idea of testing out a Good-days HackNight before creating a separate initiative.

**Comment by AbhiAgarwal** [comment]
+1 - Love this new sub-initiative theme

**Comment by ethanresnick** [comment]
Closing this, as everyone's in agreement.
